spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: dblibrary

  jpa:
    properties:
      hibernate:
        format_sql: true

    show-sql: true

logging:
  level:
    ru.otus: debug
    org.springframework: info
